### ISSUE TITLE
Decide on a PR rule

### ISSUE THREAD

**Issue by s-blu** [s-blu/miniti#26]
Do PR at all? What about reviews?

**Comment by s-blu** [comment]
Would be awesome if all changes could be reviewed by another person. Let's see if there are enough volunteers on that.

**Comment by dark-dekar** [comment]
if we are at least 2 (we are), we can fulfill this review requeriment)
I think the PR, branching, etc working agreement we have in the office is quite good.

**Comment by s-blu** [comment]
Rule: Always branch + PR from dev to do changes.
