### ISSUE TITLE
Decide on database

### ISSUE THREAD

**Issue by s-blu** [s-blu/miniti#4]

**Comment by s-blu** [comment]
Some thoughts about NoSql/Sql databases for graphQL: https://medium.com/@wtr/selecting-database-as-data-source-for-graphql-server-e3281fcefb2

I'd prefer a NoSQL solution.

**Comment by dark-dekar** [comment]
I have no recent experience with DB so, I totally trust you here :)

**Comment by s-blu** [comment]
For deciding things sake, we'll go with CouchDB here. https://couchdb.apache.org/
