### ISSUE TITLE
Decide on UI framework

### ISSUE THREAD

**Issue by s-blu** [s-blu/miniti#5]
Bulma.io? Angular Material?

**Comment by s-blu** [comment]
This article is from 2017, but offers some interesting possibilities: https://blog.bitsrc.io/11-angular-component-libraries-you-should-know-in-2018-e9f9c9d544ff

Personally, on first sight I would prefer Prime NG or, maybe even better, Onsen UI. Clarity looks very fancy, too!

**Comment by dark-dekar** [comment]
The 'problem' with Bulma is only Css. So, is really lightweight, but we'd need to code aaaaall the logic behind. 
I like Bulma, but i would only use it if: 
1. Is going to be a really simply app.
2. We wan't to learn to create a lot of things that we are using from material right now.

From the article you shared. I like the Clarity design: doesn't feel like 'another Material-like', has a lot of components, and have its own icons too.

Onsen UI looks a good option if we want to go for a PWA and have native designs for iOs and Android. If not, I think I like more the design of PrimeNG (and feels more complete) at least for the demos.

**Comment by s-blu** [comment]
We have settled to try PrimeNG https://www.primefaces.org/primeng/#/
