### ISSUE TITLE
Decide on a mascot. Design it. Love it.

### ISSUE THREAD

**Issue by s-blu** [s-blu/miniti#7]
I am still on a yeti.

**Comment by s-blu** [comment]
![mascot-draft](https://user-images.githubusercontent.com/2006600/69478064-345b5600-0dee-11ea-81b4-e876c0999ba8.jpg)
Forget about the yeti, I want a snow rabbit

**Comment by dark-dekar** [comment]
It's cute indeed

**Comment by s-blu** [comment]
Snow rabbit TinyTi will be the apps mascot. 

![favicon ico](https://user-images.githubusercontent.com/2006600/70371335-f40dd480-18d1-11ea-9b0c-28a1b8a0ee47.png)
